<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پرسپترون
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    به یک تمرین اساسی از پایه‌ای‌ترین مباحث شبکه‌های عصبی خوش آمدید! در این تمرین رویکرد متفاوتی را در پیش خواهیم گرفت و قصد داریم ساختار پرسپترون و الگوریتم آموزش آن را که در درسنامه‌های پیشین آموختید مستقیماً پیاده‌سازی کنیم. کدنویسی در این سطح به شما کمک خواهد کرد که به شکل عملی درک عمیق‌تری از نحوه‌ی کار این مدل پیدا کنید و در آینده نیز هنگام مواجه با مدل‌های مختلف شبکه‌های عصبی قادر به تحلیل آسان‌تر ساختار آن‌ها باشید. پس از طراحی پرسپترون، آن را روی مجموعه‌داده‌ی مشهور <i>گل‌های زنبق (iris)</i> آموزش داده و عملکرد دو روش مختلف آموزش پرسپترون، یعنی قاعده‌ی پرسپترون و قاعده‌ی دلتا را بر روی این مجموعه‌داده ارزیابی خواهیم کرد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [ ]:
import json
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from inspect import getsource

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در این تمرین از مجموعه‌‌داده‌ی ساده اما مشهور گل‌های زنبق (iris) استفاده خواهیم کرد. این مجموعه‌داده شامل سه دسته (نوع گیاه) است که از هر دسته 50 نمونه داده وجود دارد. هر داده دارای یک برچسب و چهار ویژگی است که در جدول زیر معرفی شده‌اند.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|SepalLengthCm|طول کاسبرگ (سانتی‌متر)|
|SepalWidthCm|عرض کاسبرگ (سانتی‌متر)|
|PetalLengthCm|طول گلبرگ (سانتی‌متر)|
|PetalWidthCm|عرض گلبرگ (سانتی‌متر)|
|Species|نوع گیاه (متغیر هدف)|

</font>
</div>
</center>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌ مجموعه‌داده را بخوانید. برای این تمرین مجموعه‌ی آزمونی در نظر گرفته نشده و هدف تنها پیاده‌سازی و تحلیل مدل است. بنابراین کل مجموعه‌داده را می‌توانید از فایل <code>iris.csv</code> موجود در پوشه‌ی مسئله خوانده و از نمونه‌های موجود در آن برای آموزش پرسپترون استفاده کنید. توجه داشته باشید که نیازی به ستون <code>Id</code> ندارید و می‌توانید آن را از دیتافریم خود حذف کنید.
</font>
</p>

In [ ]:
train_data = pd.read_csv('/content/drive/MyDrive/ML/Quera_exercise/تمرین پرسپترون/iris.csv')
train_data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
train_data['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
train_data = train_data.drop(['Id'], axis = 1)
train_data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
train_data.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    اگر به مقادیر ستون <code>Species</code> نگاه کرده باشید، دریافته‌اید که این مجموعه‌داده دارای سه کلاس <code>Iris-setosa</code> ،<code>Iris-versicolor</code> و <code>Iris-virginica</code> است.
    <br>
    از آنجا که یک پرسپترون واحد قادر به دسته‌بندی دوکلاسه هست در این تمرین قصد داریم سه مدل مختلف را آموزش دهیم که هرکدام از آن‌ها بین یک ترکیب دوتایی از سه دسته ممکن تصمیم‌گیری می‌کند. یعنی قرار است تا سه پرسپترون را به شکل زیر آموزش دهیم:
</font>
</p>
<ul dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <li>تصمیم‌گیری بین دو دسته‌ی <code>Iris-setosa</code> و <code>Iris-versicolor</code></li>
    <li>تصمیم‌گیری بین دو دسته‌ی <code>Iris-setosa</code> و <code>Iris-virginica</code></li>
    <li>تصمیم‌گیری بین دو دسته‌ی <code>Iris-versicolor</code> و <code>Iris-virginica</code></li>
</font>
</ul>
<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    این امر همچنین به ما کمک می‌کند تا به‌صورت تجربی کشف کنیم که کدام دسته از سایر دسته‌ها به‌صورت خطی تفکیک‌پذیر است.
</font>
<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    بنابراین از شما خواسته می‌شود که دیتافریم اصلی را به سه دیتافریم کوچک‌تر (با نام‌های <code>df2</code> ،<code>df1</code> و <code>df3</code>) تقسیم کنید، به شکلی که در هر دیتافریم تنها نمونه‌های مربوط به یکی از حالت‌های لیست بالا وجود داشته باشد. به عنوان مثال در دیتافریم نخست یعنی <code>df1</code> تنها نمونه‌های حالت اول یعنی دسته‌های <code>Iris-setosa</code> و <code>Iris-versicolor</code> وجود داشته باشد.
</font>

In [ ]:
df1 = train_data[train_data['Species'].isin(['Iris-setosa','Iris-versicolor'])]
df2 = train_data[train_data['Species'].isin(['Iris-setosa','Iris-virginica'])]
df3 = train_data[train_data['Species'].isin(['Iris-versicolor','Iris-virginica'])]

In [ ]:
df1

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0             5.1           3.5            1.4           0.2      Iris-setosa
1             4.9           3.0            1.4           0.2      Iris-setosa
2             4.7           3.2            1.3           0.2      Iris-setosa
3             4.6           3.1            1.5           0.2      Iris-setosa
4             5.0           3.6            1.4           0.2      Iris-setosa
..            ...           ...            ...           ...              ...
95            5.7           3.0            4.2           1.2  Iris-versicolor
96            5.7           2.9            4.2           1.3  Iris-versicolor
97            6.2           2.9            4.3           1.3  Iris-versicolor
98            5.1           2.5            3.0           1.1  Iris-versicolor
99            5.7           2.8            4.1           1.3  Iris-versicolor

[100 rows x 5 columns]

In [ ]:
df2

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[100 rows x 5 columns]

In [ ]:
df3

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
50             7.0           3.2            4.7           1.4  Iris-versicolor
51             6.4           3.2            4.5           1.5  Iris-versicolor
52             6.9           3.1            4.9           1.5  Iris-versicolor
53             5.5           2.3            4.0           1.3  Iris-versicolor
54             6.5           2.8            4.6           1.5  Iris-versicolor
..             ...           ...            ...           ...              ...
145            6.7           3.0            5.2           2.3   Iris-virginica
146            6.3           2.5            5.0           1.9   Iris-virginica
147            6.5           3.0            5.2           2.0   Iris-virginica
148            6.2           3.4            5.4           2.3   Iris-virginica
149            5.9           3.0            5.1           1.8   Iris-virginica

[100 rows x 5 columns]

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
کد زیر دیتافریم‌های شما را ذخیره می‌کند تا در انتهای نت‌بوک به فایل جواب شما اضافه شود. سه دیتافریم بالا از نظر تعداد نمونه، ستون‌ها و مقادیر موجود در ستون <code>Species</code> داوری خواهند شد. نیازی به تغییر کد نیست و کافیست تنها سلول را اجرا نمایید.
</font>

In [ ]:
df1.to_csv('df1.csv', index=False)
df2.to_csv('df2.csv', index=False)
df3.to_csv('df3.csv', index=False)

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    اکنون اگر قصد دارید می‌توانید پیش‌پردازش‌های دلخواه خود را بر روی مقادیر ویژگی‌ها انجام دهید. همچنین توجه داشته باشید مقادیر ستون برچسب را باید به شکل اعداد <code dir=ltr>+1</code> و <code dir=ltr>-1</code> کدگذاری کنید. علاوه بر این فراموش نکنید که ستون‌های ویژگی را از ستون متغیر هدف (برچسب) جدا کنید.
</font>

In [ ]:
df1 = df1.copy()

# Define a dictionary for remapping values
d = {'Iris-setosa': +1, 'Iris-versicolor': -1}

# Remap the values using map()
df1['Species'] = df1['Species'].map(d)

X1 = df1.drop(['Species'], axis =1)
y1 = df1['Species']

In [ ]:
df1

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0             5.1           3.5            1.4           0.2        1
1             4.9           3.0            1.4           0.2        1
2             4.7           3.2            1.3           0.2        1
3             4.6           3.1            1.5           0.2        1
4             5.0           3.6            1.4           0.2        1
..            ...           ...            ...           ...      ...
95            5.7           3.0            4.2           1.2       -1
96            5.7           2.9            4.2           1.3       -1
97            6.2           2.9            4.3           1.3       -1
98            5.1           2.5            3.0           1.1       -1
99            5.7           2.8            4.1           1.3       -1

[100 rows x 5 columns]

In [ ]:
df2 = df2.copy()

# Define a dictionary for remapping values
d = {'Iris-setosa': +1, 'Iris-virginica': -1}

# Remap the values using map()
df2['Species'] = df2['Species'].map(d)

X2 = df2.drop(['Species'], axis =1)
y2 = df2['Species']

In [ ]:
df2

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        1
1              4.9           3.0            1.4           0.2        1
2              4.7           3.2            1.3           0.2        1
3              4.6           3.1            1.5           0.2        1
4              5.0           3.6            1.4           0.2        1
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3       -1
146            6.3           2.5            5.0           1.9       -1
147            6.5           3.0            5.2           2.0       -1
148            6.2           3.4            5.4           2.3       -1
149            5.9           3.0            5.1           1.8       -1

[100 rows x 5 columns]

In [ ]:
df3 = df3.copy()

# Define a dictionary for remapping values
d = {'Iris-versicolor': +1, 'Iris-virginica': -1}

# Remap the values using map()
df3['Species'] = df3['Species'].map(d)

X3 = df3.drop(['Species'], axis =1)
y3 = df3['Species']

In [ ]:
df3

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
50             7.0           3.2            4.7           1.4        1
51             6.4           3.2            4.5           1.5        1
52             6.9           3.1            4.9           1.5        1
53             5.5           2.3            4.0           1.3        1
54             6.5           2.8            4.6           1.5        1
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3       -1
146            6.3           2.5            5.0           1.9       -1
147            6.5           3.0            5.2           2.0       -1
148            6.2           3.4            5.4           2.3       -1
149            5.9           3.0            5.1           1.8       -1

[100 rows x 5 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X1_scaler = scaler.fit_transform(X1)
X2_scaler = scaler.fit_transform(X2)
X3_scaler = scaler.fit_transform(X3)

In [ ]:
X1_scaler = pd.DataFrame(X1_scaler, columns=X1.columns).reset_index(drop=True)
y1 = y1.reset_index(drop=True)
df1 = pd.concat([X1_scaler, y1], axis=1)

In [ ]:
X2_scaler = pd.DataFrame(X2_scaler, columns=X2.columns).reset_index(drop=True)
y2 = y2.reset_index(drop=True)
df2 = pd.concat([X2_scaler, y2], axis=1)

In [ ]:
X3_scaler = pd.DataFrame(X3_scaler, columns=X3.columns).reset_index(drop=True)
y3 = y3.reset_index(drop=True)
df3 = pd.concat([X3_scaler, y3], axis=1)

In [ ]:
df1

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0       -0.581066      0.857135      -1.014360     -1.038248        1
1       -0.894309     -0.198450      -1.014360     -1.038248        1
2       -1.207552      0.223784      -1.083741     -1.038248        1
3       -1.364174      0.012667      -0.944978     -1.038248        1
4       -0.737687      1.068253      -1.014360     -1.038248        1
..            ...           ...            ...           ...      ...
95       0.358663     -0.198450       0.928326      0.736535       -1
96       0.358663     -0.409567       0.928326      0.914013       -1
97       1.141771     -0.409567       0.997708      0.914013       -1
98      -0.581066     -1.254036       0.095747      0.559057       -1
99       0.358663     -0.620684       0.858945      0.914013       -1

[100 rows x 5 columns]

In [ ]:
df2

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0       -0.741032      0.734325      -1.011647     -1.022316        1
1       -0.953667     -0.473447      -1.011647     -1.022316        1
2       -1.166301      0.009662      -1.059638     -1.022316        1
3       -1.272619     -0.231892      -0.963656     -1.022316        1
4       -0.847349      0.975880      -1.011647     -1.022316        1
..            ...           ...            ...           ...      ...
95       0.960046     -0.473447       0.812005      1.273795       -1
96       0.534776     -1.681218       0.716023      0.836440       -1
97       0.747411     -0.473447       0.812005      0.945779       -1
98       0.428459      0.492771       0.907987      1.273795       -1
99       0.109507     -0.473447       0.764014      0.727102       -1

[100 rows x 5 columns]

In [ ]:
df3

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0        1.119009      0.990688      -0.250779     -0.653039        1
1        0.209246      0.990688      -0.494254     -0.416431        1
2        0.967382      0.688649      -0.007304     -0.416431        1
3       -1.155400     -1.727663      -1.102941     -0.889647        1
4        0.360873     -0.217468      -0.372516     -0.416431        1
..            ...           ...            ...           ...      ...
95       0.664127      0.386610       0.357908      1.476436       -1
96       0.057618     -1.123585       0.114433      0.530003       -1
97       0.360873      0.386610       0.357908      0.766611       -1
98      -0.094009      1.594766       0.601383      1.476436       -1
99      -0.548891      0.386610       0.236171      0.293394       -1

[100 rows x 5 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    اکنون که داده‌ها را پردازش و آماده کردید نوبت به قسمت اصلی یعنی مدل می‌رسد. همانطور که در ابتدا ذکر کردیم در این تمرین دیگر خبری از کتابخانه‌ی آماده‌ی <code>scikit-learn</code> نیست. در اینجا از شما خواسته شده تا یک مدل ساده‌ی پرسپترون را به دو حالت (قاعده‌ی پرسپترون و قاعده‌ی دلتا) از صفر پیاده کنید. برای این کار قدم به قدم هر جزء این مدل را شرح خواهیم داد تا نسبت به پیاده‌‌سازی آن اقدام کنید.
    <br>
    <b>نکته: </b>
    در اعمال ریاضی و محاسباتی خود تنها از کتابخانه‌ی نامپای استفاده کنید و لیست‌های خود را نیز به شکل آرایه‌ی نامپای تعریف کنید.
    <br>
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قاعده‌ی پرسپترون
</font>
</h3>
<center>
    <img src="perceptron_rule.png">
<center>
<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
    به منظور پیاده‌سازی مدل،‌ کلاسی با نام <code>Perceptron</code> تعریف خواهیم کرد که در هنگام ساخته شدن (<code>__init__</code>) یک ویژگی مرتبط با وزن‌ها را با نام <code>weights</code> به این کلاس اضافه می‌کند. بنابراین در هنگام پیاده‌سازی توابع جهت دسترسی به وزن‌های پرسپترون می‌توانید از <code>self.weights</code> استفاده کنید.
    <br>
    اکنون هرکدام از توابع مورد نیاز این کلاس را شرح خواهیم داد تا شما به پیاده‌سازی آن‌ها بپردازید:
    <br>
    <ul dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
        <li>
        تابع <code>weighting</code> مقادیر ویژگی‌های یک نمونه را گرفته و آن را در بردار وزن ضرب نقطه‌ای می‌کند. سپس ورودی وزن‌دار شده به عنوان خروجی برگردانده می‌شود.
        </li>
        <li>
        در تابعی به نام <code>activation</code> تابع فعال‌ساز را که در اینجا تابع علامت است پیاده خواهیم کرد. این تابع، ورودی وزن‌دار را گرفته و در صورتیکه حاصل بیشتر یا مساوی صفر بود خروجی <code>1</code> و در غیر این‌صورت خروجی <code dir=ltr>-1</code> تولید می‌کند.
        </li>
        <li>
        تابع <code>predict</code> آرایه‌ای از نمونه‌ها را گرفته و آرایه‌ای شامل برچسب پیش‌بینی‌شده برای هرکدام از نمونه‌ها را بر می‌گرداند. در این تابع باید به ازای هر نمونه ابتدا آن را به کمک تابع <code>weighting</code> وزن دار کنید و حاصل را به تابع <code>activation</code> بدهید تا برچسب <code dir=ltr>+1</code> یا <code dir=ltr>-1</code> را برای نمونه تولید کند.
        </li>
        <li>
        الگوریتم اصلی پرسپترون در واقع در تابع <code>fit</code> پیاده می‌شود. این تابع ورودی‌ها و هایپرپارامترهای زیر را گرفته و سپس طبق مراحلی که شرح خواهیم داد شروع به آموزش [وزن‌های] پرسپترون می‌کند.
        </li>
    </ul>
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ورودی|توضیحات|
|:------:|:---:|
|inputs|ویژگی‌های ورودی نمونه‌های آموزشی|
|outputs|متغیر هدف (برچسب) نمونه‌‌های آموزشی|
|learning_rate|نرخ یادگیری (η)|
|epochs|تعداد دفعات آموزش بر روی تمام نمونه‌ها|

</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium; padding-right:40px;">
<font face="vazir">
در درسنامه‌ی پرسپترون اشاره کردیم که عبارت بایاس را می‌توان به کمک اضافه کردن یک ورودی ثابت <code>1</code> به ویژگی‌های ورودی تعبیه کرد. بنابراین در تابع <code>fit</code> ابتدا به اول ویژگی‌های هرکدام از نمونه‌ها عدد <code>1</code> را اضافه کنید (به عنوان مثال برای نمونه‌ی <code>inputs[i]</code>، باید <code>inputs[i][0]</code> برابر <code>1</code> باشد). با این کار یک واحد به طول بردار ویژگی نمونه‌ها اضافه خواهد شد. (فراموش نکنید که این کار را در هنگام پیش‌بینی یعنی تابع predict نیز باید انجام دهید.)
<br>
پس از آن نیاز است تا بردار وزن یعنی <code>self.weights</code> را ساخته و مقداردهی کنید. برای مقداردهی اولیه می‌توانید از اعداد تصادفی بین <code dir=ltr>0</code> تا <code dir=ltr>1</code> استفاده کنید.
<br>
سپس در یک حلقه به ازای هر دور (به تعداد <code>epochs</code>) باید یک‌بار کل مجموعه‌ی آموزشی را بررسی کنید. بنابراین در داخل این حلقه، یک حلقه‌ی دیگر خواهید داشت که هربار یکی از نمونه‌ها را بررسی می‌کند (به دلیل استفاده از روش کاهش گرادیان تصادفی در هر تکرار تنها یک نمونه بررسی و وزن‌ها آپدیت می‌شوند).
<br>
به ازای هر نمونه، ابتدا به کمک تابع <code>weighting</code> بردار ویژگی آن را در بردار وزن ضرب نقطه‌ای می‌کنیم تا ورودی وزن‌دار به دست آید. سپس حاصل به‌دست‌آمده را به تابع فعال‌سازی می‌دهیم تا مقدار خروجی مدل را تولید کند. حال با تفریق پیش‌بینی مدل از مقدار (برچسب) واقعی می‌توانیم اختلاف‌شان را به دست آوریم. سپس طبق فرمول‌های معرفی‌شده در درسنامه، با ضرب این اختلاف در نرخ یادگیری و ویژگی‌های ورودی و سپس جمع آن با مقادیر قبلی بردار وزن می‌توانیم به آپدیت بردار وزن بپردازیم.
<br>
پیشنهاد می‌شود در آخر هر دور نسبت به چاپ دقت مدل کنونی بر روی مجموعه‌ی آموزشی نیز اقدام کنید. برای این کار کافیست نمونه‌ها را به تابع <code>predict</code> بدهید تا پیش‌بینی مدل تولید شود و سپس به کمک تابع آماده‌ی <code>accuracy_score</code> دقت آن را به دست آورید.
<br>
<b>نکته: </b>
در هیچ‌کدام از توابع خود به غیر از تابع <code>fit</code> چیزی را چاپ (<code>print</code>) نکنید، در غیر این‌صورت سیستم داوری قادر به امتیازدهی به توابع شما نخواهد بود.
</font>
</p>

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score

class Perceptron:

    def __init__(self):
        self.weights = None

    def weighting(self, input):
        return np.dot(input, self.weights)


    def activation(self, weighted_input):
        return 1 if weighted_input >= 0 else -1


    def predict(self, inputs):
        inputs = np.hstack([np.ones((inputs.shape[0], 1)), inputs])
        predicted_list = []
        for x in inputs:
            weighted = self.weighting(x)
            predicted = self.activation(weighted)
            predicted_list.append(predicted)
        return predicted_list

    def fit(self, inputs, outputs, learning_rate, epochs):
        inputs = np.hstack([np.ones([inputs.shape[0],1]), inputs])
        # initializing the weights to 0
        self.weights = np.zeros(inputs.shape[1])
        # training the model n_iter times
        for epoch in range(epochs):
            predictions = []
            # loop through each input
            for xi, y in zip(inputs, outputs):
                # 1. calculate ŷ (the predicted value)
                weighted_input = self.weighting(xi)
                y_pred = self.activation(weighted_input)
                # 2. calculate Update
                # update = η * (y - ŷ)
                update = learning_rate * (y - y_pred)
                # 3. Update the weights
                # Wi = Wi + Δ(Wi)   where  Δ(Wi) = η * (y - ŷ) = update * Xi
                self.weights = self.weights + update * xi
                predictions.append(y_pred)
            acc = accuracy_score(outputs, predictions)
            print(f'Accuracy for epoch {epoch+1}: {acc}')

        return self

<h4 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش مدل
</font>
</h4>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
    پس از طراحی ساختار پرسپترون می‌توانید به کمک <code dir=ltr>Perceptron()</code> ابتدا یک نمونه از این کلاس بسازید و سپس تابع <code>fit</code> را با آرگومان‌های مناسب صدا بزنید تا آموزش مدل آغاز شود. این کار را برای هر سه حالت ورودی انجام دهید. پیشنهاد می‌شود مقادیر مختلف نرخ یادگیری مانند 0.1، 0.01، 0.001 و... را آزمایش و مقایسه کنید.
</font>
</p>

In [ ]:
lr = [0.1, 0.01, 0.001]

for i in lr:
  perceptron = Perceptron()
  p = perceptron.fit(X1_scaler, y1, learning_rate=i, epochs=10)

  print(f'Learning rate: {i}')
  print('=================================')

Accuracy for epoch 1: 0.98
Accuracy for epoch 2: 1.0
Accuracy for epoch 3: 1.0
Accuracy for epoch 4: 1.0
Accuracy for epoch 5: 1.0
Accuracy for epoch 6: 1.0
Accuracy for epoch 7: 1.0
Accuracy for epoch 8: 1.0
Accuracy for epoch 9: 1.0
Accuracy for epoch 10: 1.0
Learning rate: 0.1
=================================
Accuracy for epoch 1: 0.98
Accuracy for epoch 2: 1.0
Accuracy for epoch 3: 1.0
Accuracy for epoch 4: 1.0
Accuracy for epoch 5: 1.0
Accuracy for epoch 6: 1.0
Accuracy for epoch 7: 1.0
Accuracy for epoch 8: 1.0
Accuracy for epoch 9: 1.0
Accuracy for epoch 10: 1.0
Learning rate: 0.01
=================================
Accuracy for epoch 1: 0.98
Accuracy for epoch 2: 1.0
Accuracy for epoch 3: 1.0
Accuracy for epoch 4: 1.0
Accuracy for epoch 5: 1.0
Accuracy for epoch 6: 1.0
Accuracy for epoch 7: 1.0
Accuracy for epoch 8: 1.0
Accuracy for epoch 9: 1.0
Accuracy for epoch 10: 1.0
Learning rate: 0.001
=================================

In [ ]:
lr = [0.1, 0.01, 0.001]

for i in lr:
  perceptron = Perceptron()
  p = perceptron.fit(X2_scaler, y2, learning_rate=0.1, epochs=10)

  print(f'Learning rate: {i}')
  print('=================================')

Accuracy for epoch 1: 0.99
Accuracy for epoch 2: 1.0
Accuracy for epoch 3: 1.0
Accuracy for epoch 4: 1.0
Accuracy for epoch 5: 1.0
Accuracy for epoch 6: 1.0
Accuracy for epoch 7: 1.0
Accuracy for epoch 8: 1.0
Accuracy for epoch 9: 1.0
Accuracy for epoch 10: 1.0
Learning rate: 0.1
=================================
Accuracy for epoch 1: 0.99
Accuracy for epoch 2: 1.0
Accuracy for epoch 3: 1.0
Accuracy for epoch 4: 1.0
Accuracy for epoch 5: 1.0
Accuracy for epoch 6: 1.0
Accuracy for epoch 7: 1.0
Accuracy for epoch 8: 1.0
Accuracy for epoch 9: 1.0
Accuracy for epoch 10: 1.0
Learning rate: 0.01
=================================
Accuracy for epoch 1: 0.99
Accuracy for epoch 2: 1.0
Accuracy for epoch 3: 1.0
Accuracy for epoch 4: 1.0
Accuracy for epoch 5: 1.0
Accuracy for epoch 6: 1.0
Accuracy for epoch 7: 1.0
Accuracy for epoch 8: 1.0
Accuracy for epoch 9: 1.0
Accuracy for epoch 10: 1.0
Learning rate: 0.001
=================================

In [ ]:
lr = [0.1, 0.01, 0.001]

for i in lr:
  perceptron = Perceptron()
  p = perceptron.fit(X3_scaler, y3, learning_rate=0.1, epochs=10)

  print(f'Learning rate: {i}')
  print('=================================')

Accuracy for epoch 1: 0.97
Accuracy for epoch 2: 0.94
Accuracy for epoch 3: 0.96
Accuracy for epoch 4: 0.94
Accuracy for epoch 5: 0.94
Accuracy for epoch 6: 0.94
Accuracy for epoch 7: 0.94
Accuracy for epoch 8: 0.95
Accuracy for epoch 9: 0.96
Accuracy for epoch 10: 0.95
Learning rate: 0.1
=================================
Accuracy for epoch 1: 0.97
Accuracy for epoch 2: 0.94
Accuracy for epoch 3: 0.96
Accuracy for epoch 4: 0.94
Accuracy for epoch 5: 0.94
Accuracy for epoch 6: 0.94
Accuracy for epoch 7: 0.94
Accuracy for epoch 8: 0.95
Accuracy for epoch 9: 0.96
Accuracy for epoch 10: 0.95
Learning rate: 0.01
=================================
Accuracy for epoch 1: 0.97
Accuracy for epoch 2: 0.94
Accuracy for epoch 3: 0.96
Accuracy for epoch 4: 0.94
Accuracy for epoch 5: 0.94
Accuracy for epoch 6: 0.94
Accuracy for epoch 7: 0.94
Accuracy for epoch 8: 0.95
Accuracy for epoch 9: 0.96
Accuracy for epoch 10: 0.95
Learning rate: 0.001
=================================

<h4 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
🤔
پرسش
</font>
</h4>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
    از میان سه حالت مختلفی که برای کلاس‌های مجموعه‌داده در نظر گرفتیم، یک یا چند حالت به‌صورت خطی تفکیک‌پذیر هستند. تفکیک‌پذیر خطی بودن آن‌ها را می‌توان طبق دقت به‌دست‌آمده توسط مدل نتیجه‌گیری کرد. طبق نتایج به‌دست‌آمده در اجرای خود فکر می‌کنید کدام حالت یا حالت‌ها به‌صورت خطی تفکیک‌پذیر هستند؟ پاسخ را در متغیر <code>linearly_separable</code> به شکل یک لیست وارد کنید. به عنوان مثال اگر پاسخ شما حالت اول یعنی کلاس‌های <code>Iris-setosa</code> و <code>Iris-versicolor</code> است آنگاه <code>linearly_separable</code> را به‌صورت <code>[1]</code> و اگر پاسخ شما مثلاً حالت دوم و سوم است آن را به شکل <code dir=ltr>[2, 3]</code> مقداردهی کنید.
</font>
</p>

In [ ]:
linearly_separable = [1, 2]
linearly_separable

[1, 2]

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قاعده‌ی دلتا
</font>
</h3>
<center>
<img src="delta_rule.png">
</center>
<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
    در این حالت می‌خواهیم کلاسی با نام <code>Adaline</code> بسازیم و  مدل را با قاعده‌ی دلتا آموزش دهیم. در اینجا از روش نزول گرادیان استفاده خواهیم کرد، یعنی تمام نمونه‌های آموزشی به‌صورت همزمان بر روی آپدیت وزن تاثیر می‌گذارند (برخلاف روش نزول گرادیان تصادفی که هربار یک نمونه دیده می‌شد). کد این مدل بسیار شبیه به حالت قبلی خواهد بود و تنها نیاز است چند مورد جزئی زیر را اعمال کنید:
    <br>
    <ul dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
        <li>
        از آنجا که در این حالت از تابع فعال‌سازی خطی استفاده می‌شود تابع <code>activation</code> تنها همان ورودی وزن‌دار خود را بدون هیچ‌گونه تغییری خروجی می‌دهد.
        </li>
        <li>
        در تابع <code>prediction</code> پس از وزن‌دار کردن و عبور از تابع فعال‌سازی، باید بررسی کنید که اگر حاصل بزرگتر یا مساوی صفر بود، مقدار پیش‌بینی <code dir=ltr>+1</code> و در غیر این‌صورت <code dir=ltr>-1</code> شود.
        </li>
        <li>
        پیشنهاد می‌شود به جای اینکه یک حلقه بنویسید که خطای هر نمونه را محاسبه کند و در آخر از مجموع آن جهت آپدیت وزن استفاده کنید، همین کار را به‌صورت برداری انجام دهید (با ضرب نقطه‌ای ترانهاده‌ی ماتریس ورودی در بردار وزن).
        </li>
    </ul>
</font>
</p>

In [ ]:
class Adaline:

    def __init__(self):
        self.weights = None

    def weighting(self, input):
        return np.dot(input, self.weights)

    def activation(self, weighted_input):
        return weighted_input

    def predict(self, inputs):
        inputs = np.hstack([np.ones([inputs.shape[0],1]), inputs])
        predictions = self.activation(self.weighting(inputs))
        predictions = np.where(predictions>=0, +1, -1)
        return predictions

    def fit(self, inputs, outputs, learning_rate=0.1, epochs=64):
        inputs = np.hstack([np.ones([inputs.shape[0],1]), inputs])
        self.weights = np.zeros(inputs.shape[1])
        self.cost_ = []
        for i in range(epochs):
            activation_function_output = self.activation(self.weighting(inputs))
            errors = outputs - activation_function_output
            self.weights += learning_rate * inputs.T.dot(errors)
            cost = (errors ** 2).sum() / 2.0
            print(f'epoch {i}: cost={cost}')
			      self.cost_.append(cost)

        return self

<h4 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش مدل
</font>
</h4>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
    پس از طراحی ساختار پرسپترون می‌توانید به کمک <code dir=ltr>Adaline()</code> ابتدا یک نمونه از این کلاس بسازید و سپس تابع <code>fit</code> را با آرگومان‌های مناسب صدا بزنید تا آموزش مدل آغاز شود. این کار را برای هر سه حالت ورودی انجام دهید. پیشنهاد می‌شود مقادیر مختلف نرخ یادگیری مانند 0.1، 0.01، 0.001 و... را آزمایش و مقایسه کنید.
</font>
</p>

In [ ]:
lr = [0.1, 0.01, 0.001]

for i in lr:
  adaline = Adaline()
  a = adaline.fit(X1_scaler, y1, learning_rate=i, epochs=10)

  print(f'Learning rate: {i}')
  print('=================================')

epoch 0: cost=50.0
epoch 1: cost=40486.505357248956
epoch 2: cost=34868296.33295055
epoch 3: cost=30050618817.747196
epoch 4: cost=25899589777790.312
epoch 5: cost=2.2322012471241028e+16
epoch 6: cost=1.9238617788570345e+19
epoch 7: cost=1.6581140158669654e+22
epoch 8: cost=1.4290746461887132e+25
epoch 9: cost=1.2316730483518086e+28
Learning rate: 0.1
=================================
epoch 0: cost=50.0
epoch 1: cost=196.8746191591341
epoch 2: cost=808.3961968323352
epoch 3: cost=3343.207087026344
epoch 4: cost=13848.554225466873
epoch 5: cost=57386.20578572022
epoch 6: cost=237819.94077474528
epoch 7: cost=985593.5623134064
epoch 8: cost=4084600.0175604243
epoch 9: cost=16927846.265694614
Learning rate: 0.01
=================================
epoch 0: cost=50.0
epoch 1: cost=25.719702750255802
epoch 2: cost=13.903012452253883
epoch 3: cost=8.136552670583812
epoch 4: cost=5.3089914689440425
epoch 5: cost=3.9106351975930007
epoch 6: cost=3.2087006631836945
epoch 7: cost=2.8473001942439664
epoch 8: cost=2.6534178615304556
epoch 9: cost=2.542794950205298
Learning rate: 0.001
=================================

In [ ]:
lr = [0.1, 0.01, 0.001]

for i in lr:
  adaline = Adaline()
  a = adaline.fit(X2_scaler, y2, learning_rate=i, epochs=10)

  print(f'Learning rate: {i}')
  print('=================================')

epoch 0: cost=50.0
epoch 1: cost=41176.366362169974
epoch 2: cost=35417036.64793431
epoch 3: cost=30465187731.16743
epoch 4: cost=26205744369201.902
epoch 5: cost=2.2541831797779284e+16
epoch 6: cost=1.939018324845333e+19
epoch 7: cost=1.6679177184960915e+22
epoch 8: cost=1.43472059037845e+25
epoch 9: cost=1.234127528974733e+28
Learning rate: 0.1
=================================
epoch 0: cost=50.0
epoch 1: cost=199.71431430145455
epoch 2: cost=819.2330860651931
epoch 3: cost=3380.0333208542424
epoch 4: cost=13963.37206775009
epoch 5: cost=57701.02902131244
epoch 6: cost=238454.06455012376
epoch 7: cost=985444.7005456007
epoch 8: cost=4072501.4547601626
epoch 9: cost=16830250.360995103
Learning rate: 0.01
=================================
epoch 0: cost=50.0
epoch 1: cost=25.342208210990023
epoch 2: cost=13.360900328453116
epoch 3: cost=7.53333940468422
epoch 4: cost=4.6933015259327595
epoch 5: cost=3.3038406515078576
epoch 6: cost=2.618877693746007
epoch 7: cost=2.276230114746578
epoch 8: cost=2.100065355534107
epoch 9: cost=2.0050099143021565
Learning rate: 0.001
=================================

In [ ]:
lr = [0.1, 0.01, 0.001]

for i in lr:
  adaline = Adaline()
  a = adaline.fit(X3_scaler, y3, learning_rate=i, epochs=10)

  print(f'Learning rate: {i}')
  print('=================================')

epoch 0: cost=50.0
epoch 1: cost=21184.46595429818
epoch 2: cost=17146633.95916956
epoch 3: cost=14002385578.469849
epoch 4: cost=11436624204544.518
epoch 5: cost=9341040879477894.0
epoch 6: cost=7.629441239302381e+18
epoch 7: cost=6.23146547585331e+21
epoch 8: cost=5.089646903471844e+24
epoch 9: cost=4.1570487235200985e+27
Learning rate: 0.1
=================================
epoch 0: cost=50.0
epoch 1: cost=113.42869030717627
epoch 2: cost=389.88573038391445
epoch 3: cost=1459.0674291212433
epoch 4: cost=5560.59609466558
epoch 5: cost=21284.454981190927
epoch 6: cost=81560.93357121
epoch 7: cost=312625.94107429637
epoch 8: cost=1198394.3961935479
epoch 9: cost=4593913.6645652875
Learning rate: 0.01
=================================
epoch 0: cost=50.0
epoch 1: cost=35.84268997949122
epoch 2: cost=28.327350545288507
epoch 3: cost=24.151524408732747
epoch 4: cost=21.67315210455449
epoch 5: cost=20.074003469757212
epoch 6: cost=18.944773096357686
epoch 7: cost=18.079287434872978
epoch 8: cost=17.372416264229813
epoch 9: cost=16.769415600277433
Learning rate: 0.001
=================================

<h4 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
💭
تفکر
</font>
</h4>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir">
    مقایسه‌ی عملکرد دو مدل <code>Perceptron</code> و <code>Adaline</code> در حالتی که مجموعه‌داده به شکل خطی تفکیک‌پذیر نباشد می‌تواند به شکل عملی تفاوت میان این دو مدل را برای‌تان شفاف سازد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>داوری</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در این تمرین هرکدام از توابعی که پیاده کرده‌اید به‌صورت جداگانه مورد داوری قرار خواهد گرفت تا از عملکرد هرکدام به شکل جداگانه مطمئن شوید. البته تابع <code>fit</code> هر کلاس به منزله‌ی عملکرد کلی مدل است و جهت ارزیابی، مدل شما بر روی یک حالت تفکیک‌پذیر خطی از مجموعه‌داده iris آموزش خواهد دید و انتظار می‌رود که بتواند دقت تقریبی ۱۰۰ درصد را بر روی مجموعه‌ی آموزشی به دست آورد. علاوه بر این دیتافریم‌های اولیه و پاسخ شما به پرسش مطرح‌شده درباره‌ی تفکیک‌پذیری خطی نیز امتیازدهی خواهد شد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    سلول‌های زیر را به منظور ساخت فایل‌های کلاس‌های پیاده‌سازی شده و پاسخ خود به پرسش مطرح شده اجرا نمایید.
</font>
</p>

In [ ]:
with open("linearly_separable.json", "w") as f:
    json.dump(linearly_separable, f)
f.close()

In [ ]:
inspect_perceptron = Perceptron()
with open("Perceptron.py", "w") as f:
    f.write('import numpy as np\n')
    f.write('from sklearn.metrics import accuracy_score\n')
    f.write('class Perceptron:\n')
    f.write(getsource(inspect_perceptron.__init__)+'\n')
    f.write(getsource(inspect_perceptron.weighting)+'\n')
    f.write(getsource(inspect_perceptron.activation)+'\n')
    f.write(getsource(inspect_perceptron.predict)+'\n')
    f.write(getsource(inspect_perceptron.fit)+'\n')
f.close()

In [ ]:
inspect_adaline = Adaline()
with open("Adaline.py", "w") as f:
    f.write('import numpy as np\n')
    f.write('from sklearn.metrics import accuracy_score\n')
    f.write('class Adaline:\n')
    f.write(getsource(inspect_adaline.__init__)+'\n')
    f.write(getsource(inspect_adaline.weighting)+'\n')
    f.write(getsource(inspect_adaline.activation)+'\n')
    f.write(getsource(inspect_adaline.predict)+'\n')
    f.write(getsource(inspect_adaline.fit)+'\n')
f.close()

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ['df1.csv', 'df2.csv', 'df3.csv', 'perceptron.ipynb', 'Perceptron.py', 'Adaline.py', 'linearly_separable.json']
compress(file_names)