<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
امید به زندگی
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
به تمرین «امید به زندگی» خوش آمدید :)
    <br>
    هدف این تمرین این است که با مورد بررسی قرار دادن شاخص‌های بهداشتی، مالی و کشوری، امید به زندگی کشورها را پیش‌بینی کنیم.
    <br>
    امید به زندگی یا متوسط طول عمر (به انگلیسی: Life Expectancy) یک شاخص آماری است که نشان می‌دهد اعضای یک جامعه به‌طور میانگین چقدر عمر می‌کنند، یا به عبارت دیگر، انتظار می‌رود چقدر عمر کنند. اطلاعات بیشتر درباره‌ی امید به زندگی را می‌توانید در
<a href="https://fa.wikipedia.org/wiki/%D8%A7%D9%85%DB%8C%D8%AF_%D8%A8%D9%87_%D8%B2%D9%86%D8%AF%DA%AF%DB%8C">ویکی‌پدیا</a>
    مطالعه کنید.
    
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [54]:
import numpy as np
import pandas as pd

In [55]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
مجموعه‌داده‌ی آموزشی مسئله دارای ۲۸۴۸ سطر و ۱۸ ستون است.
    ۱۷ ستون مربوط به متغیرهای مستقل و ستون آخر هم نشانگر متغیر وابسته مسئله است.
    <br>
    در جدول زیر توضیح هر ستون را مشاهده می‌کنید. هر سطر مربوط به اطلاعات یک کشور است که در یک سال مشخص رکورد شده است.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>Country</code>|کشور مورد مطالعه|
|<code>Year</code>|سال|
|<code>Status</code>|وضعیت توسعه‌یافتگی کشور|
|<code>Population</code>|جمعیت کشور|
|<code>Hepatitis B</code>|درصد افراد نهایتاً یک ساله‌ای که در برابر هپاتیت ب ایمن شده‌اند|
|<code>Measles</code>|تعداد موارد مبتلا به سرخک گزارش شده در هر ۱۰۰۰ نفر|
|<code>Polio</code>|درصد افراد نهایتاً یک ساله‌ای که در برابر فلج اطفال ایمن شده‌اند|
|<code>Diphtheria</code>|درصد افراد نهایتاً یک ساله‌ای که در برابر دیفتری ایمن شده‌اند|
|<code>HIV/AIDS</code>|تعداد فوتی‌های ناشی از ایدز افراد نهایتاً ۴ ساله‌ای که زنده به دنیا آمده‌اند در هر ۱۰۰۰ نفر|
|<code>infant deaths</code>|تعداد فوتی‌های نوزادان در هر ۱۰۰۰ نفر|
|<code>under-five deaths</code>|تعداد فوتی‌های افراد نهایتاً ۵ ساله در هر ۱۰۰۰ نفر|
|<code>Total expenditure</code>|نسبت هزینه‌های درمانی-بهداشتی دولت به کل هزینه‌های دولت بر حسب درصد|
|<code>GDP</code>|تولید ناخالص ملی بر حسب دلار امریکا|
|<code>BMI</code>|میانگین شاخص توده بدنی کل جمعیت کشور|
|<code>thinness 1-19 years</code>|میزان شیوع لاغری میان افراد نهایتاً ۱۹ ساله بر حسب درصد|
|<code>Alcohol</code>|میزان لیتر مصرف الکل بین افراد بیشتر از ۱۵ سال|
|<code>Schooling</code>|تعداد سالی که افراد تحصیل می‌کنند|
|<code>Life expectancy</code>|امید به زندگی یا متوسط طول عمر|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
     مجموعه‌ی آزمون (تست) مانند مجموعه‌ی آموزش است با این تفاوت که ستون <code>Life expectancy</code> را ندارد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>train.csv</code> و نمونه‌های آزمون که باید مقدار متغیر هدف آن‌ها را پیش‌بینی کنید در فایل <code>test.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از مجموعه‌ی آموزش را به عنوان مجموعه‌ی اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [56]:
train_data = pd.read_csv('/content/drive/MyDrive/ML/Quera_exercise/امید به زندگی/train.csv')
train_data

,Country,Year,Status,Population,Hepatitis B,Measles,Polio,Diphtheria,HIV/AIDS,infant deaths,under-five deaths,Total expenditure,GDP,BMI,thinness 1-19 years,Alcohol,Schooling,Life expectancy
0,Afghanistan,2015,Developing,33736494.0,65.0,1154,6.0,65.0,0.1,62,83,8.16,584.259210,19.1,17.2,0.01,10.1,65.0
1,Afghanistan,2014,Developing,327582.0,62.0,492,58.0,62.0,0.1,64,86,8.18,612.696514,18.6,17.5,0.01,10.0,59.9
2,Afghanistan,2013,Developing,31731688.0,64.0,430,62.0,64.0,0.1,66,89,8.13,631.744976,18.1,17.7,0.01,9.9,59.9
3,Afghanistan,2012,Developing,3696958.0,67.0,2787,67.0,67.0,0.1,69,93,8.52,669.959000,17.6,17.9,0.01,9.8,59.5
4,Afghanistan,2011,Developing,2978599.0,68.0,3013,68.0,68.0,0.1,71,97,7.87,63.537231,17.2,18.2,0.01,9.5,59.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2843,Zimbabwe,2004,Developing,12777511.0,68.0,31,67.0,65.0,33.6,27,42,7.13,454.366654,27.1,9.4,4.36,9.2,44.3
2844,Zimbabwe,2003,Developing,12633897.0,7.0,998,7.0,68.0,36.7,26,41,6.52,453.351155,26.7,9.8,4.06,9.5,44.5
2845,Zimbabwe,2002,Developing,125525.0,73.0,304,73.0,71.0,39.8,25,40,6.53,57.348340,26.3,1.2,4.43,10.0,44.8
2846,Zimbabwe,2001,Developing,12366165.0,76.0,529,76.0,75.0,42.1,25,39,6.16,548.587312,25.9,1.6,1.72,9.8,45.3
2847,Zimbabwe,2000,Developing,12222251.0,79.0,1483,78.0,78.0,43.5,24,39,7.10,547.358878,25.5,11.0,1.68,9.8,46.0

In [57]:
test_data = pd.read_csv('/content/drive/MyDrive/ML/Quera_exercise/امید به زندگی/test.csv')
test_data

,Country,Year,Status,Population,Hepatitis B,Measles,Polio,Diphtheria,HIV/AIDS,infant deaths,under-five deaths,Total expenditure,GDP,BMI,thinness 1-19 years,Alcohol,Schooling
0,Burundi,2015,Developing,119927.0,94.0,9,94.0,94.0,0.7,21,31,NaN,33.681223,18.7,7.3,NaN,10.6
1,Burundi,2014,Developing,989179.0,95.0,0,95.0,95.0,0.7,22,32,7.54,312.748979,18.2,7.4,0.01,10.6
2,Burundi,2013,Developing,96186.0,96.0,0,96.0,96.0,1.0,22,32,8.30,282.755525,17.6,7.4,0.01,10.5
3,Burundi,2012,Developing,931971.0,96.0,49,96.0,96.0,1.2,22,33,8.21,265.285651,17.1,7.5,0.01,10.3
4,Burundi,2011,Developing,94358.0,96.0,129,95.0,96.0,1.5,22,33,8.58,26.479973,16.6,7.6,4.16,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Papua New Guinea,2004,Developing,6161517.0,6.0,1385,59.0,62.0,1.5,11,15,8.39,637.361621,4.4,1.5,0.58,7.6
76,Papua New Guinea,2003,Developing,61724.0,67.0,3863,62.0,68.0,1.4,11,14,6.79,588.358260,39.6,1.5,0.59,7.2
77,Papua New Guinea,2002,Developing,5862316.0,6.0,17620,54.0,61.0,1.4,11,14,7.69,511.665773,38.9,1.5,0.61,6.9
78,Papua New Guinea,2001,Developing,5716152.0,59.0,4023,52.0,55.0,1.3,11,14,6.68,539.415280,38.2,1.5,0.68,6.6
79,Papua New Guinea,2000,Developing,5572222.0,57.0,7135,51.0,59.0,1.1,11,14,3.98,631.946853,37.5,1.6,0.73,6.2

In [58]:
train_data.describe()

,Year,Population,Hepatitis B,Measles,Polio,Diphtheria,HIV/AIDS,infant deaths,under-five deaths,Total expenditure,GDP,BMI,thinness 1-19 years,Alcohol,Schooling,Life expectancy
count,2848.000000,2.204000e+03,2306.000000,2848.000000,2829.000000,2829.000000,2848.000000,2848.000000,2848.000000,2627.000000,2406.000000,2816.000000,2816.000000,2660.000000,2688.000000,2848.000000
mean,2007.500000,1.283457e+07,81.076756,2083.082163,82.682220,82.451396,1.756461,28.359902,39.500000,5.935577,7664.398813,38.503374,4.847230,4.638932,12.060156,69.347402
std,4.610582,6.196094e+07,25.019068,10249.107207,23.434954,23.693936,5.148935,117.188032,159.800866,2.504439,14466.241793,19.955485,4.443695,4.064721,3.320160,9.528332
min,2000.000000,3.400000e+01,1.000000,0.000000,3.000000,2.000000,0.100000,0.000000,0.000000,0.370000,1.681350,1.000000,0.100000,0.010000,0.000000,36.300000
25%,2003.750000,1.967585e+05,77.000000,0.000000,78.000000,78.000000,0.100000,0.000000,0.000000,4.240000,477.541713,19.500000,1.600000,0.930000,10.200000,63.500000
50%,2007.500000,1.391756e+06,92.000000,16.000000,93.000000,93.000000,0.100000,3.000000,4.000000,5.760000,1841.086830,43.900000,3.300000,3.785000,12.400000,72.200000
75%,2011.250000,7.438947e+06,97.000000,336.750000,97.000000,97.000000,0.700000,20.000000,25.000000,7.530000,6265.658907,56.200000,7.125000,7.810000,14.300000,75.800000
max,2015.000000,1.293859e+09,99.000000,212183.000000,99.000000,99.000000,50.600000,1800.000000,2500.000000,17.600000,119172.741800,77.600000,27.700000,17.870000,20.700000,89.000000

In [59]:
test_data.describe()

,Year,Population,Hepatitis B,Measles,Polio,Diphtheria,HIV/AIDS,infant deaths,under-five deaths,Total expenditure,GDP,BMI,thinness 1-19 years,Alcohol,Schooling
count,80.000000,8.000000e+01,69.000000,80.000000,80.00000,80.000000,80.000000,80.000000,80.00000,75.000000,79.000000,80.000000,80.000000,75.000000,80.000000
mean,2007.500000,1.083521e+07,77.086957,14701.800000,77.81250,77.725000,1.436250,103.300000,137.56250,5.740533,2311.013841,28.802500,4.970000,3.760933,9.966250
std,4.638856,2.453566e+07,24.863592,30750.224294,22.38902,23.847073,1.645573,128.264403,164.53316,1.570423,3924.703153,17.793271,3.543095,3.434557,3.603864
min,2000.000000,1.284000e+03,6.000000,0.000000,7.00000,3.000000,0.100000,0.000000,0.00000,1.300000,12.178928,2.500000,1.300000,0.010000,3.900000
25%,2003.750000,1.369482e+05,66.000000,1.000000,64.75000,68.750000,0.100000,10.000000,13.00000,4.600000,163.753021,14.500000,1.850000,0.815000,7.500000
50%,2007.500000,1.651091e+06,89.000000,426.000000,86.00000,86.000000,0.950000,23.500000,35.50000,5.300000,539.415280,22.250000,3.850000,2.960000,9.650000
75%,2011.250000,7.307833e+06,95.000000,6421.000000,95.00000,95.250000,1.925000,188.500000,259.00000,6.590000,1968.067182,44.375000,7.825000,5.785000,12.550000
max,2015.000000,9.736677e+07,99.000000,131441.000000,99.00000,99.000000,5.300000,490.000000,608.00000,11.490000,16348.531210,61.200000,11.900000,12.120000,16.400000

In [60]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2848 entries, 0 to 2847
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country               2848 non-null   object
 1   Year                  2848 non-null   int64
 2   Status                2848 non-null   object
 3   Population            2204 non-null   float64
 4   Hepatitis B           2306 non-null   float64
 5   Measles               2848 non-null   int64
 6   Polio                 2829 non-null   float64
 7   Diphtheria            2829 non-null   float64
 8   HIV/AIDS              2848 non-null   float64
 9   infant deaths         2848 non-null   int64
 10  under-five deaths     2848 non-null   int64
 11  Total expenditure     2627 non-null   float64
 12  GDP                   2406 non-null   float64
 13  BMI                   2816 non-null   float64
 14  thinness  1-19 years  2816 non-null   float64
 15  Alcohol               2660 non-null   float64
 16  Schooling             2688 non-null   float64
 17  Life expectancy       2848 non-null   float64
dtypes: float64(12), int64(4), object(2)
memory usage: 400.6+ KB

In [61]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country               80 non-null     object
 1   Year                  80 non-null     int64
 2   Status                80 non-null     object
 3   Population            80 non-null     float64
 4   Hepatitis B           69 non-null     float64
 5   Measles               80 non-null     int64
 6   Polio                 80 non-null     float64
 7   Diphtheria            80 non-null     float64
 8   HIV/AIDS              80 non-null     float64
 9   infant deaths         80 non-null     int64
 10  under-five deaths     80 non-null     int64
 11  Total expenditure     75 non-null     float64
 12  GDP                   79 non-null     float64
 13  BMI                   80 non-null     float64
 14  thinness  1-19 years  80 non-null     float64
 15  Alcohol               75 non-null     float64
 16  Schooling             80 non-null     float64
dtypes: float64(11), int64(4), object(2)
memory usage: 10.8+ KB

In [62]:
train_data.isnull().sum()

Country                   0
Year                      0
Status                    0
Population              644
Hepatitis B             542
Measles                   0
Polio                    19
Diphtheria               19
HIV/AIDS                  0
infant deaths             0
under-five deaths         0
Total expenditure       221
GDP                     442
BMI                      32
thinness  1-19 years     32
Alcohol                 188
Schooling               160
Life expectancy           0
dtype: int64

In [63]:
test_data.isnull().sum()

Country                  0
Year                     0
Status                   0
Population               0
Hepatitis B             11
Measles                  0
Polio                    0
Diphtheria               0
HIV/AIDS                 0
infant deaths            0
under-five deaths        0
Total expenditure        5
GDP                      1
BMI                      0
thinness  1-19 years     0
Alcohol                  5
Schooling                0
dtype: int64

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی که در فصل‌های گذشته آموختید، استفاده کنید.
    <br>
    تکنیک‌هایی که استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
</font>
</p>

In [64]:
from sklearn.model_selection import train_test_split

X = train_data.drop('Life expectancy', axis=1)
y = train_data['Life expectancy']


X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


X_test = test_data.copy()


print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(2278, 17)
(570, 17)
(80, 17)

In [65]:
from sklearn.impute import SimpleImputer


imputer = SimpleImputer(strategy='median')


numeric_cols = X_train.select_dtypes(
    include=['int64','float64']
).columns


# train
X_train[numeric_cols] = imputer.fit_transform(
    X_train[numeric_cols]
)


# validation
X_val[numeric_cols] = imputer.transform(
    X_val[numeric_cols]
)


# test
X_test[numeric_cols] = imputer.transform(
    X_test[numeric_cols]
)


print("Train NaN:", X_train.isna().sum().sum())
print("Val NaN:", X_val.isna().sum().sum())
print("Test NaN:", X_test.isna().sum().sum())

Train NaN: 0
Val NaN: 0
Test NaN: 0

In [66]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


# train
X_train['Status'] = label_encoder.fit_transform(
    X_train['Status']
)


# validation
X_val['Status'] = label_encoder.transform(
    X_val['Status']
)


# test
X_test['Status'] = label_encoder.transform(
    X_test['Status']
)

In [67]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd


encoder = OneHotEncoder(
    sparse_output=False,
    handle_unknown='ignore'
)


# train
encoded_train = encoder.fit_transform(
    X_train[['Country']]
)


# validation
encoded_val = encoder.transform(
    X_val[['Country']]
)


# test
encoded_test = encoder.transform(
    X_test[['Country']]
)



one_hot_train = pd.DataFrame(
    encoded_train,
    columns=encoder.get_feature_names_out(['Country']),
    index=X_train.index
)


one_hot_val = pd.DataFrame(
    encoded_val,
    columns=encoder.get_feature_names_out(['Country']),
    index=X_val.index
)


one_hot_test = pd.DataFrame(
    encoded_test,
    columns=encoder.get_feature_names_out(['Country']),
    index=X_test.index
)



X_train = pd.concat(
    [
        X_train.drop('Country', axis=1),
        one_hot_train
    ],
    axis=1
)


X_val = pd.concat(
    [
        X_val.drop('Country', axis=1),
        one_hot_val
    ],
    axis=1
)


X_test = pd.concat(
    [
        X_test.drop('Country', axis=1),
        one_hot_test
    ],
    axis=1
)



print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(2278, 194)
(570, 194)
(80, 194)

In [68]:
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()


X_train_scaled = scaler.fit_transform(
    X_train
)


X_val_scaled = scaler.transform(
    X_val
)


X_test_scaled = scaler.transform(
    X_test
)


print(X_train_scaled.shape)
print(X_val_scaled.shape)
print(X_test_scaled.shape)

(2278, 194)
(570, 194)
(80, 194)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
</font>
</p>

<h3 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    استفاده از <code>scikit-learn</code>
</font>
</h3>


<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    برای الگوریتم رگرسیون چند‌جمله‌ای پکیج یکتایی در کتابخانه‌ی <code>scikit-learn</code> وجود ندارد. بنابراین برای استفاده از این الگوریتم، می‌بایست ابتدا ویژگی‌های دیتافریم را با استفاده از کلاس <code>PolynomialFeatures</code> که در پکیج <code>preprocessing</code> قرار دارد، به ویژگی‌های چندجمله‌ای تبدیل کنید. سپس از آن ویژگی‌های تغییریافته (<code>transformed</code>) برای آموزش یک رگرسیون خطی معمولی استفاده کنید.
    <br>
    برخی از آرگومان‌های مهم این کلاس در جدول زیر آمده است، اما برای مطالعه کامل‌تر مستندات می‌توانید به <a href="https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html">این لینک</a> مراجعه فرمایید.

</font>
</div>
    
<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<br>

|آرگومان|نوع|توضیحات|
|:------:|:--------:|:---:|
|<code>degree</code>|<code>int</code> یا <code>tuple</code>|درجه چند جمله‌ای را نشان می‌دهد. به‌صورت پیش‌فرض عدد <code>2</code> است.<br> اگر به شکل <code>tuple</code> باشد، به شکل <code dir=ltr>(min_degree, max_degree)</code> تفسیر می‌شود.|
|<code>include_bias</code>|<code>bool</code>|آیا شامل بایاس باشد یا خیر. <br> در صورت <code>True</code> بودن، عدد <code>1</code> هم به چندجمله‌ای افزوده می‌شود. <br> (به این معنی که چندجمله‌ای‌های تولید‌شده حداقل از درجه‌ی <code>min_degree</code> و حداکثر از مرتبه‌ی <code>max_degree</code> خواهند بود.)|
    
</font>
</div>
</center>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    کلاس <code>PolynomialFeatures</code> دارای سه متد به شرح زیر است:
</font>
</p>


<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|اسم متد|توضیحات|
|:------:|:---:|
|<code>fit</code>|تعداد جملات چندجمله‌ای خروجی را حساب می‌کند|
|<code>transform</code>|داده‌ی ورودی را به جملات چند‌جمله‌ای تبدیل می‌کند|
|<code>fit_transform</code>|ابتدا تابع <code>fit</code> و سپس تابع <code>transform</code> را اجرا می‌کند|

</font>
</div>
</center>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش مدل
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در سلول پایین با استفاده از کتابخانه‌ی <code>scikit-learn</code> مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
    <br>
    برای ساختن ویژگی‌های چندجمله‌ای، شیء <code>poly_transformer</code> را مقداردهی کنید. بعداً در سلول جواب‌ساز این شیء ذخیره شده و در زمان داوری، مورد ارزیابی واقع خواهد شد.
    <br>
     سپس با ویژگی‌های چندجمله‌ای خروجی <code>poly_transformer</code> مدل رگرسیون خطی را آموزش دهید و آن را در شیء <code>model</code> ذخیره کنید. متغیر <code>model</code> در فرآیند داوری مورد ارزیابی واقع خواهد شد. بنابراین اطمینان حاصل کنید که از جنس <code>LinearRegression</code> باشد؛ در غیر این صورت نمره‌ای دریافت نخواهید کرد!
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>
<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>r2_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی مجموعه‌ی آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>50</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

In [69]:
from sklearn.feature_selection import SelectKBest, f_regression


selector = SelectKBest(
    score_func=f_regression,
    k=30
)


X_train_selected = selector.fit_transform(
    X_train_scaled,
    y_train
)


X_val_selected = selector.transform(
    X_val_scaled
)

X_test_selected = selector.transform(
    X_test_scaled
)

print("X_train_selected shape:", X_train_selected.shape)
print("X_val_selected shape:", X_val_selected.shape)
print("X_test_selected shape:", X_test_selected.shape)

X_train_selected shape: (2278, 30)
X_val_selected shape: (570, 30)
X_test_selected shape: (80, 30)

In [70]:
from sklearn.preprocessing import PolynomialFeatures


poly_transformer = PolynomialFeatures(
    degree=2,
    include_bias=False
)


X_train_poly = poly_transformer.fit_transform(
    X_train_selected
)


X_val_poly = poly_transformer.transform(
    X_val_selected
)


X_test_poly = poly_transformer.transform(
    X_test_selected
)


print(X_train_poly.shape)
print(X_val_poly.shape)
print(X_test_poly.shape)

(2278, 495)
(570, 495)
(80, 495)

In [71]:
from sklearn.linear_model import Ridge


model = Ridge(
    alpha=0.1
)


model.fit(
    X_train_poly,
    y_train
)

Ridge(alpha=0.1)

In [72]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np


y_train_pred = model.predict(X_train_poly)

y_val_pred = model.predict(X_val_poly)



print("Train R2:",
      r2_score(y_train, y_train_pred))


print("Validation R2:",
      r2_score(y_val, y_val_pred))


print("MAE:",
      mean_absolute_error(y_val, y_val_pred))


print("RMSE:",
      np.sqrt(mean_squared_error(y_val, y_val_pred)))

Train R2: 0.8955275645940555
Validation R2: 0.8811276059225439
MAE: 2.545775713732966
RMSE: 3.2666671683258803

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پس از مهندسی ویژگی و مدلسازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در مجموعه‌ی آزمون استفاده کنید و نتایج را در قالب جدول (<code>dataframe</code>) زیر آماده کنید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>Life expectancy</code>|امید به زندگی پیش‌بینی‌شده|
    
</font>
</div>
</center>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    توجه داشته باشید که نام دیتافریم باید <code>submission</code> باشد؛ در غیر این‌صورت، سامانه‌ی داوری قادر به ارزیابی خروجی شما نخواهد بود.
    این دیتافریم تنها شامل ۱ ستون با اسم <code>Life expectancy</code> است و ۸۰ سطر دارد.
    <br>
    به ازای هر سطر موجود در دیتافریم <code>test</code>، باید یک مقدار پیش‌بینی‌شده داشته باشید.
    به‌عنوان مثال جدول زیر، ۵ سطر ابتدایی دیتافریم <code>submission</code> را نشان می‌دهد. البته در جواب شما، اعداد ستون <code>Life expectancy</code> ممکن است متفاوت باشد.
</font>
</p>

<center>
<div style="direction: ltr;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
||<code>Life expectancy</code>|
|:----:|:-----:|
|0|70.1|
|1|65.2|
|2|50.0|
|3|81.72|
|4|75.25|

</font>
</div>
</center>

In [73]:
y_test_pred = model.predict(
    X_test_poly
)


submission = pd.DataFrame(
    y_test_pred,
    columns=['Life expectancy']
)


submission

    Life expectancy
0         66.945461
1         66.632953
2         66.443394
3         65.964395
4         65.625905
..              ...
75        57.069041
76        63.021363
77        59.728936
78        61.850355
79        62.111748

[80 rows x 1 columns]

In [74]:
print(y_val.min())
print(y_val.max())

print(y_val_pred.min())
print(y_val_pred.max())

43.5
89.0
41.78679362010696
85.76003633947535

In [75]:
submission.describe()

       Life expectancy
count        80.000000
mean         64.332064
std           8.807083
min          46.343639
25%          59.507230
50%          64.120996
75%          69.220815
max          81.029897

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)


joblib.dump(poly_transformer, 'poly_transformer')
joblib.dump(model, 'model')
submission.to_csv('submission.csv', index=False)

file_names = ['poly_transformer', 'model', 'submission.csv', 'life_expectancy.ipynb']
compress(file_names)

<h4 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
راهنمایی
</font>
</h4>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    ۱. در مراحل پیش‌پردازش از تغییر مقیاس ویژگی استفاده کنید.
    <br>
    ۲. مقادیر گم‌شده‌ی ویژگی‌ها را بررسی و مدیریت کنید.
</font>
</p>